// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_500 from "./routes/_500.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.tsx";
import * as $item from "./routes/item.tsx";
import * as $user from "./routes/user.tsx";
import * as $Comments from "./islands/Comments.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_500.tsx": $_500,
    "./routes/_app.tsx": $_app,
    "./routes/index.tsx": $index,
    "./routes/item.tsx": $item,
    "./routes/user.tsx": $user,
  },
  islands: {
    "./islands/Comments.tsx": $Comments,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
